POKE_API_ERROR = "Error: Pokemon api error: Test"
NAME_ERROR = "Error: Pokemon NOT FOUND possible name error"
TRANSLATOR_API_ERROR = "Error: Translator api error: Test"
TEST_ENDPOINT = "test/"
TEST_NAME = "test_name"
QUERY = "test string"
YODA_STYLE = "yoda.json"
TEST_TEXT = "test text"
